USE [master]
GO

/****** Object:  Database [TimesheetDB]   ******/
CREATE DATABASE [TimesheetDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimesheetDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TimesheetDB.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimesheetDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TimesheetDB_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimesheetDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TimesheetDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TimesheetDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TimesheetDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TimesheetDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TimesheetDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TimesheetDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TimesheetDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TimesheetDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TimesheetDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TimesheetDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TimesheetDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TimesheetDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TimesheetDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TimesheetDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TimesheetDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TimesheetDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TimesheetDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TimesheetDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TimesheetDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TimesheetDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TimesheetDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TimesheetDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TimesheetDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TimesheetDB] SET  MULTI_USER 
GO

ALTER DATABASE [TimesheetDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TimesheetDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TimesheetDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TimesheetDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TimesheetDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TimesheetDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TimesheetDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [TimesheetDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TimesheetDB] SET  READ_WRITE 
GO


USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[AuditLog]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AuditLog](
	[AuditID] [int] IDENTITY(1,1) NOT NULL,
	[PackageName] [varchar](255) NULL,
	[TaskName] [varchar](255) NULL,
	[OperationType] [varchar](255) NULL,
	[EntityType] [varchar](255) NULL,
	[RowCount] [int] NULL,
	[AuditTime] [datetime] NULL,
	[FileProcessed] [varchar](500) NULL,
	[EmployeeID] [int] NULL,
	[EmployeeName] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[AuditID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AuditLog] ADD  DEFAULT (getdate()) FOR [AuditTime]
GO



USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[Client]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Client](
	[ClientID] [int] IDENTITY(1,1) NOT NULL,
	[ClientName] [varchar](255) NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ClientName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Client] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[Description]    ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Description](
	[DescriptionID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](100) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[DescriptionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Description] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO

USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[Employee]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [varchar](100) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Employee] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO

USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[Expense]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Expense](
	[ExpenseID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[Month] [date] NULL,
	[ExpenseDescription] [varchar](255) NULL,
	[Type] [varchar](255) NULL,
	[ZarCost] [decimal](5, 2) NULL,
	[CreatedAt] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ExpenseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Expense] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO

ALTER TABLE [dbo].[Expense]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO


USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[Leave]    ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Leave](
	[LeaveID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[TypeOfLeave] [varchar](255) NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[NumberOfDays] [decimal](4, 1) NULL,
	[ApprovalObtained] [varchar](255) NULL,
	[SickNoteProvided] [varchar](255) NULL,
	[ContactInformation] [varchar](1000) NULL,
	[SubmissionDate] [date] NULL,
	[CreatedAt] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[LeaveID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Leave] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO

ALTER TABLE [dbo].[Leave]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO


USE [TimesheetDB]
GO

/****** Object:  Table [dbo].[Timesheet]   ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Timesheet](
	[TimesheetID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[DayOfWeek] [varchar](255) NULL,
	[ClientID] [int] NOT NULL,
	[ProjectName] [varchar](255) NULL,
	[DescriptionID] [int] NOT NULL,
	[Billable] [varchar](255) NULL,
	[Comments] [varchar](255) NULL,
	[TotalHours] [decimal](5, 2) NULL,
	[StartTime] [time](7) NULL,
	[EndTime] [time](7) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[TimesheetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Timesheet] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO

ALTER TABLE [dbo].[Timesheet]  WITH CHECK ADD FOREIGN KEY([ClientID])
REFERENCES [dbo].[Client] ([ClientID])
GO

ALTER TABLE [dbo].[Timesheet]  WITH CHECK ADD FOREIGN KEY([DescriptionID])
REFERENCES [dbo].[Description] ([DescriptionID])
GO

ALTER TABLE [dbo].[Timesheet]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO


